'use client';

import { useState, useCallback, useMemo } from 'react';

const SR_COLUMNS: { col: string; label: string; hint?: string }[] = [
  { col: 'first_name',      label: 'First Name',           hint: 'auto-generated' },
  { col: 'last_name',       label: 'Last Name',            hint: 'auto-generated' },
  { col: 'student_email',   label: 'Student Email',        hint: 'auto-generated' },
  { col: 'district_name',   label: 'District Name' },
  { col: 'school_name',     label: 'School Name' },
  { col: 'class_name',      label: 'Class Name' },
  { col: 'teacher_name',    label: 'Teacher Name' },
  { col: 'current_grade',   label: 'Grade' },
  { col: 'gender',          label: 'Gender' },
  { col: 'hispanic',        label: 'Hispanic',             hint: 'true/false' },
  { col: 'ell',             label: 'ELL',                  hint: 'true/false' },
  { col: 'frl',             label: 'FRL',                  hint: 'true/false' },
  { col: 'iep',             label: 'IEP',                  hint: 'true/false' },
  { col: 'ethnicity',       label: 'Ethnicity' },
  { col: 'home_language',   label: 'Home Language' },
  { col: 'session_name',    label: 'Session Name' },
  { col: 'course_id',       label: 'Course ID' },
  { col: 'response_type',   label: 'Response Type' },
  { col: 'question',        label: 'Question' },
  { col: 'answer',          label: 'Answer / Transcript' },
  { col: 'harvard_attribute', label: 'Harvard Attribute',  hint: 'per node' },
  { col: 'harvard_score',   label: 'Harvard Score' },
  { col: 'casel_attribute', label: 'CASEL Attribute',      hint: 'per node' },
  { col: 'casel_score',     label: 'CASEL Score' },
  { col: 'url',             label: 'Media URL' },
  { col: 'answer_date',     label: 'Answer Date' },
  { col: 'source_id',       label: 'Source ID' },
];

const HARVARD_ATTRIBUTES = [
  '', 'curiosity', 'grit', 'perspective_taking', 'gratitude', 'purpose', 'self_control',
];

const CASEL_ATTRIBUTES = [
  '', 'self_awareness', 'self_management', 'social_awareness',
  'relationship_skills', 'responsible_decision_making',
];

const DEFAULT_COLUMN_MAPPINGS: Record<string, string> = {
  answer:        'transcript',
  url:           'media_url',
  answer_date:   'created_at',
  question:      'node_title',
  response_type: 'media_type',
};

// Columns auto-generated by the import engine — hide mapping UI for these
const AUTO_GENERATED_COLS = new Set(['first_name', 'last_name', 'student_email']);
// Columns set via per-node response config — hide right-panel mapping UI
const PER_NODE_COLS = new Set(['harvard_attribute', 'casel_attribute']);

type FormInfo = {
  formId: string;
  formName: string | null;
  customLabel: string | null;
  sampleTitle: string | null;
  totalSteps: number;
  imported: number;
  isImported: boolean;
};

type NodeInfo = {
  nodeId: string;
  nodeTitle: string;
  hasMedia: boolean;
  sampleTranscript: string | null;
  samplePollOption: string | null;
  count: number;
};

type NodeRoleValue =
  | { role: 'skip' }
  | { role: 'response'; harvardAttribute?: string; caselAttribute?: string }
  | { role: 'metadata'; targetColumn: string; sourceField: 'transcript' | 'poll_option' };

type RunResult = {
  inserted?: number;
  skipped?: number;
  wouldInsert?: number;
  wouldSkip?: number;
  sample?: Record<string, unknown>[];
  error?: string;
};

// ── Small components ──────────────────────────────────────────────────────

function RoleBtn({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) {
  return (
    <button
      onClick={onClick}
      className={`px-2 py-0.5 text-xs rounded border transition-colors ${
        active
          ? 'bg-blue-600 text-white border-blue-600'
          : 'bg-white text-gray-600 border-gray-300 hover:border-blue-400 hover:text-blue-600'
      }`}
    >
      {children}
    </button>
  );
}

function NodeCard({
  node,
  role,
  formId,
  onRoleChange,
}: {
  node: NodeInfo;
  role: NodeRoleValue;
  formId: string;
  onRoleChange: (r: NodeRoleValue) => void;
}) {
  const mediaIcon = node.hasMedia ? '🎥' : node.samplePollOption ? '☑️' : '📝';
  const preview = node.sampleTranscript ?? node.samplePollOption ?? '';
  const rawUrl = `/api/admin/videoask-import/raw-sample?formId=${encodeURIComponent(formId)}&nodeId=${encodeURIComponent(node.nodeId)}`;

  return (
    <div className="border border-gray-200 rounded-lg p-3 bg-white space-y-2">
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0">
          <span className="text-sm font-medium text-gray-900">{mediaIcon} {node.nodeTitle}</span>
          <span className="ml-2 text-xs text-gray-400">{node.count} responses</span>
          {preview && (
            <p className="text-xs text-gray-500 mt-0.5 line-clamp-2">{preview.slice(0, 120)}{preview.length > 120 ? '…' : ''}</p>
          )}
        </div>
        <a href={rawUrl} target="_blank" rel="noreferrer"
          title="Inspect raw JSON"
          className="flex-shrink-0 text-xs text-gray-300 hover:text-blue-500 transition-colors font-mono mt-0.5">
          {'{ }'}
        </a>
      </div>
      <div className="flex items-center gap-1.5 flex-wrap">
        <RoleBtn active={role.role === 'skip'} onClick={() => onRoleChange({ role: 'skip' })}>Skip</RoleBtn>
        <RoleBtn active={role.role === 'response'} onClick={() => onRoleChange({ role: 'response' })}>Response</RoleBtn>
        <RoleBtn active={role.role === 'metadata'} onClick={() => onRoleChange({ role: 'metadata', targetColumn: 'current_grade', sourceField: 'transcript' })}>Metadata →</RoleBtn>

        {role.role === 'metadata' && (
          <>
            <select
              value={role.targetColumn}
              onChange={e => onRoleChange({ ...role, targetColumn: e.target.value })}
              className="text-xs border border-gray-300 rounded px-1.5 py-0.5 bg-white text-gray-700 focus:outline-none focus:ring-1 focus:ring-blue-400"
            >
              {SR_COLUMNS
                .filter(c => !AUTO_GENERATED_COLS.has(c.col) && !PER_NODE_COLS.has(c.col))
                .map(c => <option key={c.col} value={c.col}>{c.label}</option>)}
            </select>
            <select
              value={role.sourceField}
              onChange={e => onRoleChange({ ...role, sourceField: e.target.value as 'transcript' | 'poll_option' })}
              className="text-xs border border-gray-300 rounded px-1.5 py-0.5 bg-white text-gray-700 focus:outline-none focus:ring-1 focus:ring-blue-400"
            >
              <option value="transcript">Transcript</option>
              <option value="poll_option">Poll answer</option>
            </select>
          </>
        )}
      </div>

      {/* Per-node Harvard/CASEL attribute selectors (only for Response nodes) */}
      {role.role === 'response' && (
        <div className="flex items-center gap-2 flex-wrap pt-1 border-t border-gray-100">
          <div className="flex items-center gap-1">
            <span className="text-xs text-gray-500 whitespace-nowrap">Harvard:</span>
            <select
              value={role.harvardAttribute ?? ''}
              onChange={e => onRoleChange({ ...role, harvardAttribute: e.target.value || undefined })}
              className="text-xs border border-gray-300 rounded px-1.5 py-0.5 bg-white text-gray-700 focus:outline-none focus:ring-1 focus:ring-blue-400"
            >
              {HARVARD_ATTRIBUTES.map(a => (
                <option key={a} value={a}>{a || '— none —'}</option>
              ))}
            </select>
          </div>
          <div className="flex items-center gap-1">
            <span className="text-xs text-gray-500 whitespace-nowrap">CASEL:</span>
            <select
              value={role.caselAttribute ?? ''}
              onChange={e => onRoleChange({ ...role, caselAttribute: e.target.value || undefined })}
              className="text-xs border border-gray-300 rounded px-1.5 py-0.5 bg-white text-gray-700 focus:outline-none focus:ring-1 focus:ring-blue-400"
            >
              {CASEL_ATTRIBUTES.map(a => (
                <option key={a} value={a}>{a || '— none —'}</option>
              ))}
            </select>
          </div>
        </div>
      )}
    </div>
  );
}

function MappingRow({
  srCol, label, hint, sourceColumns,
  mappingType, sourceCol, staticVal,
  onMappingTypeChange, onSourceColChange, onStaticValChange,
  autoGenerated, metadataCoveredBy, perNodeControlled,
}: {
  srCol: string; label: string; hint?: string; sourceColumns: string[];
  mappingType: 'source' | 'static' | 'none'; sourceCol: string; staticVal: string;
  onMappingTypeChange: (t: 'source' | 'static' | 'none') => void;
  onSourceColChange: (v: string) => void;
  onStaticValChange: (v: string) => void;
  autoGenerated?: boolean;
  metadataCoveredBy?: string | null;
  perNodeControlled?: boolean;
}) {
  if (autoGenerated) {
    return (
      <div className="grid grid-cols-[140px_1fr] gap-2 items-center py-1.5 border-b border-gray-100 last:border-0">
        <div>
          <span className="text-sm text-gray-700">{label}</span>
          <span className="block text-xs text-gray-400 font-mono">{srCol}</span>
        </div>
        <span className="text-xs text-indigo-500 italic">→ auto-generated per student</span>
      </div>
    );
  }

  if (perNodeControlled) {
    return (
      <div className="grid grid-cols-[140px_1fr] gap-2 items-center py-1.5 border-b border-gray-100 last:border-0">
        <div>
          <span className="text-sm text-gray-700">{label}</span>
          {hint && <span className="ml-1 text-xs text-gray-400">({hint})</span>}
          <span className="block text-xs text-gray-400 font-mono">{srCol}</span>
        </div>
        <span className="text-xs text-blue-500 italic">→ set per Response node (left panel)</span>
      </div>
    );
  }

  if (metadataCoveredBy) {
    return (
      <div className="grid grid-cols-[140px_1fr] gap-2 items-center py-1.5 border-b border-gray-100 last:border-0">
        <div>
          <span className="text-sm text-gray-700">{label}</span>
          <span className="block text-xs text-gray-400 font-mono">{srCol}</span>
        </div>
        <span className="text-xs text-emerald-600 italic">→ from &ldquo;{metadataCoveredBy}&rdquo; metadata</span>
      </div>
    );
  }

  return (
    <div className="grid grid-cols-[140px_100px_1fr] gap-2 items-center py-1.5 border-b border-gray-100 last:border-0">
      <div>
        <span className="text-sm text-gray-700">{label}</span>
        {hint && <span className="ml-1 text-xs text-gray-400">({hint})</span>}
        <span className="block text-xs text-gray-400 font-mono">{srCol}</span>
      </div>
      <select
        value={mappingType}
        onChange={e => onMappingTypeChange(e.target.value as 'source' | 'static' | 'none')}
        className="text-xs border border-gray-300 rounded px-1.5 py-1 bg-white text-gray-700 focus:outline-none focus:ring-1 focus:ring-blue-400"
      >
        <option value="none">— skip —</option>
        <option value="source">From column</option>
        <option value="static">Static value</option>
      </select>
      {mappingType === 'source' && (
        <select
          value={sourceCol}
          onChange={e => onSourceColChange(e.target.value)}
          className="text-xs border border-gray-300 rounded px-1.5 py-1 bg-white text-gray-700 focus:outline-none focus:ring-1 focus:ring-blue-400"
        >
          <option value="">— choose column —</option>
          {sourceColumns.map(c => <option key={c} value={c}>{c}</option>)}
        </select>
      )}
      {mappingType === 'static' && (
        <input
          type="text"
          value={staticVal}
          onChange={e => onStaticValChange(e.target.value)}
          placeholder="Static value…"
          className="text-xs border border-gray-300 rounded px-2 py-1 bg-white text-gray-700 focus:outline-none focus:ring-1 focus:ring-blue-400"
        />
      )}
      {mappingType === 'none' && <div />}
    </div>
  );
}

// ── Main page ──────────────────────────────────────────────────────────────

export default function VideoAskImportPage() {
  const [view, setView] = useState<'list' | 'configure' | 'result'>('list');
  const [forms, setForms] = useState<FormInfo[]>([]);
  const [loadingForms, setLoadingForms] = useState(false);
  const [formsError, setFormsError] = useState('');

  const [selectedForm, setSelectedForm] = useState<FormInfo | null>(null);
  const [nodes, setNodes] = useState<NodeInfo[]>([]);
  const [nodeRoles, setNodeRoles] = useState<Record<string, NodeRoleValue>>({});
  const [sourceColumns] = useState<string[]>([
    'id', 'form_id', 'node_id', 'node_title', 'node_text', 'media_type',
    'media_url', 'share_url', 'transcript', 'created_at', 'contact_email', 'form_share_id',
  ]);
  const [totalSteps, setTotalSteps] = useState<number | null>(null);
  const [loadingPreview, setLoadingPreview] = useState(false);

  const [mappingTypes, setMappingTypes] = useState<Record<string, 'source' | 'static' | 'none'>>({});
  const [sourceCols, setSourceCols] = useState<Record<string, string>>({});
  const [staticVals, setStaticVals] = useState<Record<string, string>>({});

  const [saving, setSaving] = useState(false);
  const [saveMsg, setSaveMsg] = useState('');
  const [dryRunning, setDryRunning] = useState(false);
  const [dryResult, setDryResult] = useState<RunResult | null>(null);
  const [importing, setImporting] = useState(false);
  const [runResult, setRunResult] = useState<RunResult | null>(null);
  const [updating, setUpdating] = useState(false);
  const [updateResult, setUpdateResult] = useState<{ updated?: number; error?: string } | null>(null);

  // Rename / delete state
  const [editingFormId, setEditingFormId] = useState<string | null>(null);
  const [editingLabel, setEditingLabel] = useState('');

  // Columns covered by metadata nodes: col → node title
  const metadataCoveredCols = useMemo(() => {
    const map = new Map<string, string>();
    for (const [nodeId, role] of Object.entries(nodeRoles)) {
      if (role.role !== 'metadata') continue;
      const node = nodes.find(n => n.nodeId === nodeId);
      map.set(role.targetColumn, node?.nodeTitle ?? nodeId);
    }
    return map;
  }, [nodeRoles, nodes]);

  async function discoverForms() {
    setLoadingForms(true);
    setFormsError('');
    try {
      const res = await fetch('/api/admin/videoask-import/discover');
      const json = await res.json();
      if (json.error) { setFormsError(json.error); return; }
      setForms(json.forms ?? []);
    } finally {
      setLoadingForms(false);
    }
  }

  const loadFormConfig = useCallback(async (form: FormInfo) => {
    setSelectedForm(form);
    setView('configure');
    setLoadingPreview(true);
    setDryResult(null);
    setRunResult(null);
    setSaveMsg('');

    try {
      const [previewRes, configRes] = await Promise.all([
        fetch(`/api/admin/videoask-import/preview?formId=${encodeURIComponent(form.formId)}`),
        fetch(`/api/admin/videoask-import/configs?formId=${encodeURIComponent(form.formId)}`),
      ]);
      const [previewJson, configJson] = await Promise.all([previewRes.json(), configRes.json()]);

      // Set nodes + default roles (media nodes → response, others → skip)
      const fetchedNodes: NodeInfo[] = previewJson.nodes ?? [];
      setNodes(fetchedNodes);
      setTotalSteps(previewJson.totalSteps ?? 0);

      // Init mapping state
      const initTypes: Record<string, 'source' | 'static' | 'none'> = {};
      const initSource: Record<string, string> = {};
      const initStatic: Record<string, string> = {};
      for (const { col } of SR_COLUMNS) {
        initTypes[col] = 'none';
        initSource[col] = '';
        initStatic[col] = '';
      }
      for (const [srCol, stepCol] of Object.entries(DEFAULT_COLUMN_MAPPINGS)) {
        initTypes[srCol] = 'source';
        initSource[srCol] = stepCol;
      }

      // Default node roles: media → response, else → skip
      const initRoles: Record<string, NodeRoleValue> = {};
      for (const n of fetchedNodes) {
        initRoles[n.nodeId] = n.hasMedia ? { role: 'response' } : { role: 'skip' };
      }

      // Overlay saved config
      if (configJson.config) {
        const saved = configJson.config;
        for (const [srCol, stepCol] of Object.entries(saved.column_mappings ?? {}) as [string, string][]) {
          if (stepCol) { initTypes[srCol] = 'source'; initSource[srCol] = stepCol; }
        }
        for (const [srCol, val] of Object.entries(saved.static_values ?? {}) as [string, string][]) {
          if (val) { initTypes[srCol] = 'static'; initStatic[srCol] = val; }
        }
        if (saved.nodeRoles) {
          for (const [nodeId, role] of Object.entries(saved.nodeRoles) as [string, NodeRoleValue][]) {
            initRoles[nodeId] = role;
          }
        }
      }

      setMappingTypes(initTypes);
      setSourceCols(initSource);
      setStaticVals(initStatic);
      setNodeRoles(initRoles);
    } finally {
      setLoadingPreview(false);
    }
  }, []);

  function buildConfig() {
    const columnMappings: Record<string, string> = {};
    const staticValues: Record<string, string> = {};
    for (const { col } of SR_COLUMNS) {
      if (mappingTypes[col] === 'source' && sourceCols[col]) columnMappings[col] = sourceCols[col];
      else if (mappingTypes[col] === 'static' && staticVals[col]) staticValues[col] = staticVals[col];
    }
    return { columnMappings, staticValues };
  }

  async function saveConfig() {
    if (!selectedForm) return;
    setSaving(true);
    setSaveMsg('');
    const { columnMappings, staticValues } = buildConfig();
    try {
      const res = await fetch('/api/admin/videoask-import/configs', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ formId: selectedForm.formId, columnMappings, staticValues, nodeRoles }),
      });
      const json = await res.json();
      setSaveMsg(json.error ? `Error: ${json.error}` : 'Saved.');
    } finally {
      setSaving(false);
    }
  }

  async function dryRun() {
    if (!selectedForm) return;
    setDryRunning(true);
    setDryResult(null);
    const { columnMappings, staticValues } = buildConfig();
    try {
      const res = await fetch('/api/admin/videoask-import/run', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ formId: selectedForm.formId, columnMappings, staticValues, nodeRoles, dryRun: true }),
      });
      setDryResult(await res.json());
    } finally {
      setDryRunning(false);
    }
  }

  async function runUpdate() {
    if (!selectedForm) return;
    setUpdating(true);
    setUpdateResult(null);
    const { columnMappings, staticValues } = buildConfig();
    try {
      const res = await fetch('/api/admin/videoask-import/run', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ formId: selectedForm.formId, columnMappings, staticValues, nodeRoles, updateExisting: true }),
      });
      setUpdateResult(await res.json());
    } finally {
      setUpdating(false);
    }
  }

  async function runImport() {
    if (!selectedForm) return;
    setImporting(true);
    setRunResult(null);
    const { columnMappings, staticValues } = buildConfig();
    try {
      const res = await fetch('/api/admin/videoask-import/run', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ formId: selectedForm.formId, columnMappings, staticValues, nodeRoles }),
      });
      const json = await res.json();
      setRunResult(json);
      if (!json.error) { setView('result'); discoverForms(); }
    } finally {
      setImporting(false);
    }
  }

  function displayName(f: FormInfo) {
    return f.customLabel ?? f.formName ?? (f.formId.slice(0, 8) + '…');
  }

  function startRename(f: FormInfo, e: React.MouseEvent) {
    e.stopPropagation();
    setEditingFormId(f.formId);
    setEditingLabel(f.customLabel ?? f.formName ?? '');
  }

  async function saveRename(formId: string) {
    const label = editingLabel.trim();
    setEditingFormId(null);
    await fetch('/api/admin/videoask-import/discover', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: 'rename', formId, label }),
    });
    setForms(prev => prev.map(f => f.formId === formId ? { ...f, customLabel: label || null } : f));
  }

  async function deleteForm(formId: string, e: React.MouseEvent) {
    e.stopPropagation();
    if (!confirm('Remove this form from the list? It won\'t be deleted from VideoAsk.')) return;
    await fetch('/api/admin/videoask-import/discover', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: 'delete', formId }),
    });
    setForms(prev => prev.filter(f => f.formId !== formId));
  }

  const responseNodeCount = Object.values(nodeRoles).filter(r => r.role === 'response').length;
  const metadataNodeCount = Object.values(nodeRoles).filter(r => r.role === 'metadata').length;

  return (
    <div className="h-full flex flex-col overflow-hidden">
      {/* Header */}
      <div className="flex-shrink-0 px-6 pt-5 pb-4 border-b border-gray-200 bg-white">
        <div className="flex items-center gap-3">
          {view !== 'list' && (
            <button
              onClick={() => { setView('list'); setSelectedForm(null); }}
              className="text-gray-400 hover:text-gray-600 transition-colors"
            >
              <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
                <path d="M11 4L6 9l5 5" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </button>
          )}
          <div>
            <h1 className="text-lg font-semibold text-gray-900">VideoAsk Import</h1>
            <p className="text-sm text-gray-500">
              {view === 'list' && 'Import VideoAsk pilot responses into Student Responses.'}
              {view === 'configure' && selectedForm && (
                <>
                  {displayName(selectedForm)}
                  {totalSteps !== null && !loadingPreview && (
                    <span className="ml-2 text-xs text-gray-400">{totalSteps} responses</span>
                  )}
                </>
              )}
              {view === 'result' && 'Import complete.'}
            </p>
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-hidden">

        {/* ── LIST VIEW ── */}
        {view === 'list' && (
          <div className="h-full overflow-y-auto p-6 max-w-2xl">
            <button
              onClick={discoverForms}
              disabled={loadingForms}
              className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors mb-6"
            >
              {loadingForms ? (
                <>
                  <svg className="animate-spin w-4 h-4" viewBox="0 0 24 24" fill="none">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/>
                  </svg>
                  Scanning…
                </>
              ) : 'Find VideoAsk Pilots'}
            </button>

            {formsError && (
              <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">{formsError}</div>
            )}

            {forms.length > 0 && (
              <div className="space-y-2">
                {forms.map(f => (
                  <div
                    key={f.formId}
                    className={`group w-full flex items-center justify-between px-4 py-3 bg-white border rounded-lg transition-colors text-left ${
                      f.isImported ? 'border-green-200 hover:border-green-300' : 'border-gray-200 hover:border-blue-300'
                    } ${editingFormId === f.formId ? '' : 'hover:bg-blue-50 cursor-pointer'}`}
                    onClick={() => editingFormId !== f.formId && loadFormConfig(f)}
                  >
                    <div className="min-w-0 flex-1 pr-2">
                      {editingFormId === f.formId ? (
                        <input
                          autoFocus
                          value={editingLabel}
                          onChange={e => setEditingLabel(e.target.value)}
                          onBlur={() => saveRename(f.formId)}
                          onKeyDown={e => {
                            if (e.key === 'Enter') saveRename(f.formId);
                            if (e.key === 'Escape') setEditingFormId(null);
                          }}
                          onClick={e => e.stopPropagation()}
                          placeholder="Enter a name…"
                          className="w-full text-sm font-medium border border-blue-400 rounded px-2 py-0.5 focus:outline-none focus:ring-1 focus:ring-blue-400"
                        />
                      ) : (
                        <div className="flex items-center gap-2">
                          <span className="text-sm font-medium text-gray-900 truncate">{displayName(f)}</span>
                          {f.isImported && (
                            <span className="flex-shrink-0 text-xs px-2 py-0.5 rounded-full bg-green-100 text-green-700 border border-green-200 font-medium">
                              ✓ Imported
                            </span>
                          )}
                        </div>
                      )}
                      <span className="block text-xs text-gray-500 mt-0.5 truncate">
                        {f.totalSteps} response{f.totalSteps !== 1 ? 's' : ''}
                        {f.isImported && ` · ${f.imported} imported`}
                        {f.sampleTitle && ` · ${f.sampleTitle}`}
                        {!f.formName && !f.customLabel && ` · ${f.formId}`}
                      </span>
                    </div>
                    <div className="flex items-center gap-1 flex-shrink-0" onClick={e => e.stopPropagation()}>
                      {/* Rename button */}
                      <button
                        onClick={e => startRename(f, e)}
                        title="Rename"
                        className="opacity-0 group-hover:opacity-100 p-1.5 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded transition-all"
                      >
                        <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
                          <path d="M9 2l2 2L4 11H2V9L9 2z" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>
                        </svg>
                      </button>
                      {/* Delete button */}
                      <button
                        onClick={e => deleteForm(f.formId, e)}
                        title="Remove from list"
                        className="opacity-0 group-hover:opacity-100 p-1.5 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded transition-all"
                      >
                        <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
                          <path d="M2 3.5h9M5 3.5V2.5h3v1M10 3.5l-.7 7H3.7L3 3.5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>
                        </svg>
                      </button>
                      {/* Navigate arrow */}
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="text-gray-400 ml-0.5">
                        <path d="M5 3l4 4-4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                      </svg>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {!loadingForms && forms.length === 0 && (
              <p className="text-sm text-gray-500">Click the button above to scan for VideoAsk pilots.</p>
            )}
          </div>
        )}

        {/* ── CONFIGURE VIEW ── */}
        {view === 'configure' && selectedForm && (
          <div className="flex h-full overflow-hidden">

            {/* Left: node roles */}
            <div className="w-1/2 border-r border-gray-200 flex flex-col overflow-hidden">
              <div className="flex-shrink-0 px-4 pt-3 pb-2 border-b border-gray-100 bg-gray-50">
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider">
                  Questions in this form
                </p>
                {!loadingPreview && nodes.length > 0 && (
                  <p className="text-xs text-gray-400 mt-0.5">
                    {responseNodeCount} response node{responseNodeCount !== 1 ? 's' : ''}
                    {metadataNodeCount > 0 && ` · ${metadataNodeCount} metadata node${metadataNodeCount !== 1 ? 's' : ''}`}
                  </p>
                )}
              </div>
              <div className="flex-1 overflow-y-auto p-3 space-y-2">
                {loadingPreview ? (
                  <p className="text-sm text-gray-400 p-2">Loading…</p>
                ) : nodes.length > 0 ? nodes.map(node => (
                  <NodeCard
                    key={node.nodeId}
                    node={node}
                    formId={selectedForm.formId}
                    role={nodeRoles[node.nodeId] ?? { role: 'skip' }}
                    onRoleChange={r => setNodeRoles(prev => ({ ...prev, [node.nodeId]: r }))}
                  />
                )) : (
                  <p className="text-sm text-gray-400 p-2">No nodes found.</p>
                )}
              </div>
            </div>

            {/* Right: column mappings + actions */}
            <div className="w-1/2 flex flex-col overflow-hidden">
              <div className="flex-shrink-0 px-4 pt-3 pb-2 border-b border-gray-100 bg-gray-50">
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider">
                  Column mappings
                </p>
                <p className="text-xs text-gray-400 mt-0.5">Applied to Response nodes</p>
              </div>
              <div className="flex-1 overflow-y-auto p-4">
                {SR_COLUMNS.map(({ col, label, hint }) => (
                  <MappingRow
                    key={col}
                    srCol={col} label={label} hint={hint}
                    sourceColumns={sourceColumns}
                    mappingType={mappingTypes[col] ?? 'none'}
                    sourceCol={sourceCols[col] ?? ''}
                    staticVal={staticVals[col] ?? ''}
                    onMappingTypeChange={t => setMappingTypes(prev => ({ ...prev, [col]: t }))}
                    onSourceColChange={v => setSourceCols(prev => ({ ...prev, [col]: v }))}
                    onStaticValChange={v => setStaticVals(prev => ({ ...prev, [col]: v }))}
                    autoGenerated={AUTO_GENERATED_COLS.has(col)}
                    metadataCoveredBy={metadataCoveredCols.get(col) ?? null}
                    perNodeControlled={PER_NODE_COLS.has(col)}
                  />
                ))}
              </div>

              {/* Actions bar */}
              <div className="flex-shrink-0 border-t border-gray-200 px-4 pt-3 pb-4 bg-white space-y-2">
                {saveMsg && (
                  <p className={`text-xs ${saveMsg.startsWith('Error') ? 'text-red-500' : 'text-green-600'}`}>{saveMsg}</p>
                )}
                <div className="flex gap-2 flex-wrap">
                  <button
                    onClick={saveConfig}
                    disabled={saving}
                    className="px-3 py-1.5 border border-gray-300 text-sm text-gray-700 rounded-lg hover:bg-gray-50 disabled:opacity-50 transition-colors"
                  >
                    {saving ? 'Saving…' : 'Save mapping'}
                  </button>
                  <button
                    onClick={dryRun}
                    disabled={dryRunning || loadingPreview}
                    className="px-3 py-1.5 border border-blue-300 text-sm text-blue-700 rounded-lg hover:bg-blue-50 disabled:opacity-50 transition-colors"
                  >
                    {dryRunning ? 'Previewing…' : 'Preview import'}
                  </button>
                  <button
                    onClick={runUpdate}
                    disabled={updating || loadingPreview}
                    className="px-3 py-1.5 border border-amber-300 text-sm text-amber-700 rounded-lg hover:bg-amber-50 disabled:opacity-50 transition-colors"
                  >
                    {updating ? 'Updating…' : 'Update existing'}
                  </button>
                </div>
                {updateResult && (
                  <p className={`text-xs ${updateResult.error ? 'text-red-500' : 'text-amber-700'}`}>
                    {updateResult.error ? `Update error: ${updateResult.error}` : `✓ Updated ${updateResult.updated} existing rows`}
                  </p>
                )}

                {dryResult && (
                  <div className="p-3 bg-gray-50 border border-gray-200 rounded-lg text-sm space-y-2">
                    {dryResult.error ? (
                      <p className="text-red-600">Error: {dryResult.error}</p>
                    ) : (
                      <>
                        <p className="text-gray-700">
                          <strong>{dryResult.wouldInsert}</strong> rows to import
                          {(dryResult.wouldSkip ?? 0) > 0 && (
                            <>, <strong>{dryResult.wouldSkip}</strong> already imported (skipped)</>
                          )}
                        </p>
                        {dryResult.sample && dryResult.sample.length > 0 && (
                          <div>
                            <p className="text-xs font-medium text-gray-500 mb-1">Sample output row:</p>
                            <pre className="text-xs text-gray-600 bg-white border border-gray-200 rounded p-2 overflow-x-auto max-h-40">
                              {JSON.stringify(dryResult.sample[0], null, 2)}
                            </pre>
                          </div>
                        )}
                        {(dryResult.wouldInsert ?? 0) > 0 && (
                          <button
                            onClick={runImport}
                            disabled={importing}
                            className="w-full py-2 bg-green-600 text-white text-sm font-medium rounded-lg hover:bg-green-700 disabled:opacity-50 transition-colors"
                          >
                            {importing ? 'Importing…' : `Import ${dryResult.wouldInsert} rows into student_responses`}
                          </button>
                        )}
                      </>
                    )}
                  </div>
                )}

                {runResult?.error && (
                  <p className="text-sm text-red-600">Import error: {runResult.error}</p>
                )}
              </div>
            </div>
          </div>
        )}

        {/* ── RESULT VIEW ── */}
        {view === 'result' && runResult && (
          <div className="h-full overflow-y-auto p-6 max-w-md">
            <div className="p-4 bg-green-50 border border-green-200 rounded-xl mb-4">
              <p className="text-green-800 font-medium">Import complete!</p>
              <p className="text-sm text-green-700 mt-1">
                <strong>{runResult.inserted}</strong> rows inserted
                {(runResult.skipped ?? 0) > 0 && (
                  <>, <strong>{runResult.skipped}</strong> already existed (skipped)</>
                )}
              </p>
            </div>
            <div className="flex gap-2">
              <button
                onClick={() => { setView('list'); setSelectedForm(null); setRunResult(null); }}
                className="px-4 py-2 border border-gray-300 text-sm text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
              >
                Back to list
              </button>
              {selectedForm && (
                <button
                  onClick={() => loadFormConfig(selectedForm)}
                  className="px-4 py-2 border border-blue-300 text-sm text-blue-700 rounded-lg hover:bg-blue-50 transition-colors"
                >
                  Re-configure
                </button>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
